---

- name: "stat {{ elasticsearch_config_elasticsearch_yml }}"
  stat:
    path: "{{ elasticsearch_config_elasticsearch_yml }}"
  register: t_elasticsearch_config_elasticsearch_yml

- block:
    - name: init elasticsearch.yml
      copy:
        src: "{{ elasticsearch_dist_active }}/config/elasticsearch.yml"
        dest: "{{ elasticsearch_config_elasticsearch_yml }}"
        remote_src: yes
        owner: "{{ elasticsearch_admin_user }}"
        group: "{{ elasticsearch_group }}"
        mode: "0640"
      register: t_elasticsearch_config_elasticsearch_yml_init

  when: not t_elasticsearch_config_elasticsearch_yml.stat.exists


- name: update elasticsearch.yml
  lineinfile:
    path: "{{ elasticsearch_config_elasticsearch_yml }}"
    regexp: "^{{ item.name }}:"
    line: "{{ item.name }}: {{ item.value }}"
    state: "{{ item.state | d('present') }}"
    backrefs: "{{ item.backrefs | d(false) }}"
    insertafter: "{{ item.insertafter | d('^#\\s*' + item.name + ':') }}"
  when: item.state is defined or (item.value is not none and item.value is not false)
  loop: "{{ elasticsearch_conf_elasticsearch_yml_settings }}"
  register: t_elasticsearch_config_elasticsearch_yml_settings



- name: set t_elasticsearch_config_elasticsearch_yml_update
  set_fact:
    t_elasticsearch_config_elasticsearch_yml_update: "{{ t_elasticsearch_config_elasticsearch_yml_init.changed or t_elasticsearch_config_elasticsearch_yml_settings.changed }}"
