---

- name: "stat {{ elasticsearch_config_jvm_options }}"
  stat:
    path: "{{ elasticsearch_config_jvm_options }}"
  register: t_elasticsearch_config_jvm_options

- block:

    - name: init jvm.options
      copy:
        src: "{{ elasticsearch_dist_active }}/config/jvm.options"
        dest: "{{ elasticsearch_config_jvm_options }}"
        remote_src: yes
        owner: "{{ elasticsearch_admin_user }}"
        group: "{{ elasticsearch_group }}"
        mode: "0640"
      register: t_elasticsearch_config_jvm_options_init

  when: not t_elasticsearch_config_jvm_options.stat.exists


- name: set jvm.options
  lineinfile:
    path: "{{ elasticsearch_config_jvm_options }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | d('present') }}"
    backrefs: "{{ item.backrefs | d(false) }}"
  loop: "{{ elasticsearch_conf_jvm_options_settings }}"
  register: t_elasticsearch_conf_jvm_options_settings



- name: set t_elasticsearch_config_jvm_options_update
  set_fact:
    t_elasticsearch_config_jvm_options_update: "{{ t_elasticsearch_config_jvm_options_init.changed or t_elasticsearch_conf_jvm_options_settings.changed }}"
