---

- name: "stat {{ elasticsearch_config_log4j2_properties }}"
  stat:
    path: "{{ elasticsearch_config_log4j2_properties }}"
  register: t_elasticsearch_config_log4j2_properties

- block:
    - name: init log4j2.properties
      copy:
        src: "{{ elasticsearch_dist_active }}/config/log4j2.properties"
        dest: "{{ elasticsearch_config_log4j2_properties }}"
        remote_src: yes
        owner: "{{ elasticsearch_admin_user }}"
        group: "{{ elasticsearch_group }}"
        mode: "0640"
      register: t_elasticsearch_config_log4j2_properties_init

  when: not t_elasticsearch_config_log4j2_properties.stat.exists


- name: update log4j2.properties
  lineinfile:
    path: "{{ elasticsearch_config_log4j2_properties }}"
    regexp: "^{{ item.name }}:"
    line: "{{ item.name }}: {{ item.value }}"
    state: "{{ item.state | d('present') }}"
    backrefs: "{{ item.backrefs | d(false) }}"
    insertafter: "{{ item.insertafter | d('^#' + item.name + ':') }}"
  when: item.state is defined or (item.value is not none and item.value is not false)
  loop: "{{ elasticsearch_conf_log4j2_properties_settings }}"
  register: t_elasticsearch_conf_log4j2_properties_settings



- name: set t_elasticsearch_config_log4j2_properties_update
  set_fact:
    t_elasticsearch_config_log4j2_properties_update: "{{ t_elasticsearch_config_log4j2_properties_init.changed or t_elasticsearch_conf_log4j2_properties_settings.changed }}"
