---

# no password
- block:

    - name: stat password file
      stat:
        path: "{{ elasticsearch_credentials_dir }}/{{ internal_user }}.password"
      register: t_elasticsearch_internal_user_password_file


    # no password file
    - block:

        - name: create password
          command: apg -m 64 -n 1 -M LNSC
          register: t_elasticsearch_internal_user_password_cmd

        - name: refine password
          set_fact:
            t_elasticsearch_internal_user_password: "{{ t_elasticsearch_internal_user_password_cmd.stdout | trim }}"

      when: not t_elasticsearch_internal_user_password_file.stat.exists


    # with password file
    - block:

        - name: reload password file
          command: "cat '{{ elasticsearch_credentials_dir }}/{{ internal_user }}.password'"
          changed_when: no
          register: t_elasticsearch_internal_user_password_file_content

        - name: refine password
          set_fact:
            t_elasticsearch_internal_user_password: "{{ t_elasticsearch_internal_user_password_file_content.stdout | trim }}"

      when: t_elasticsearch_internal_user_password_file.stat.exists


    - name: set password
      set_fact:
        "{{ 'elasticsearch_internal_user_' ~ internal_user ~ '_password' }}": "{{ t_elasticsearch_internal_user_password }}"


  when: (("elasticsearch_internal_user_" + internal_user + "_password") not in vars) and (("elasticsearch_internal_user_" + internal_user + "_password") not in hostvars)


# with password
- block:

    - name: refine password
      set_fact:
        t_elasticsearch_internal_user_password: "{{ hostvars['elasticsearch_internal_user_' + internal_user + '_password'] | d(vars['elasticsearch_internal_user_' + internal_user + '_password']) }}"

  when: (("elasticsearch_internal_user_" + internal_user + "_password") in vars) or (("elasticsearch_internal_user_" + internal_user + "_password") in hostvars)


# save password
- name: save password
  copy:
    content: "{{ t_elasticsearch_internal_user_password }}"
    dest: "{{ elasticsearch_credentials_dir }}/{{ internal_user }}.password"
    mode: "0600"
    owner: "{{ elasticsearch_admin_user }}"
    group: "{{ elasticsearch_group }}"
